quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/pos_db_sync

# Hibernate ORM Configuration
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.packages=com.posdb.sync.entity

# JWT Configuration
smallrye.jwt.sign.key.location=keys/privateKey.pem
mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=pos-db-sync
mp.jwt.verify.audience=pos-mobile-app

# Basic Auth for Admin APIs
admin.username=admin
admin.password.hash=$2a$10$Aebna1FlgrNoM0wyxXw8I.C0vlkA684I4xO.b5HHMUL8IY36Zo3HO

# Logging Configuration
quarkus.log.level=INFO
quarkus.log.category."com.posdb.sync".level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] %m%n

# Security Configuration
quarkus.http.auth.permission.public.paths=/api/v1/admin/*,/api/v1/pos/*,/api/v1/auth/login, /api/v1/user/change-password
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/api/v1/*
quarkus.http.auth.permission.authenticated.policy=authenticated

pos.sync.batch.size=500

quarkus.http.port=9090

quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.security".level=TRACE
